#!/bin/bash

ROOT_DIR=$(git rev-parse --show-toplevel)
if [ -s ${ROOT_DIR}/.eslintrc ] ; then
	echo -e "\nValidating JavaScript:\n"

	files=$(git diff --cached --name-only --diff-filter=ACM | grep -E "^(app|src)/.*\.jsx?$")

	ESLINT="${ROOT_DIR}/node_modules/.bin/eslint -c .eslintrc"
	# ESLINT="eslint"

	for file in ${files}; do
		result=$(${ESLINT} ${file})
		if [ $? -eq 0 ]; then
			echo -e "\t\033[32mJSLint Passed: ${file}\033[0m"
		else
			echo -e "\t\033[31mJSLint Failed: ${file}\033[0m ${result}"
			pass=false
		fi
	done

	echo -e "\nJavaScript validation complete\n"

	if ! $pass; then
		echo -e "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass JSLint but do not. Please fix the JSLint errors and try again.\n"
		exit 1
	else
		echo -e "\033[42mCOMMIT SUCCEEDED\033[0m\n"
	fi
fi
